# Generated by Django 5.2.5 on 2025-08-30 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='room_id',
            new_name='room',
        ),
    ]
