# Generated by Django 5.2.5 on 2025-08-31 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_app', '0002_rename_room_id_booking_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='checkin_time',
            field=models.TimeField(default='15:00'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='checkout_time',
            field=models.TimeField(default='11:00'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='timezone',
            field=models.CharField(default='Asia/Bahrain', max_length=64),
        ),
    ]
