# Generated by Django 5.2.5 on 2025-09-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_app', '0002_booking_user'),
        ('HMS_app', '0002_profile'),
    ]

    operations = [
    ]
