# Generated by Django 5.2.5 on 2025-08-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_app', '0003_rename_hotel_id_room_hotel_remove_room_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimage',
            name='image_url',
            field=models.CharField(),
        ),
    ]
