# Generated by Django 5.2.5 on 2025-08-31 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_app', '0003_alter_hotel_checkin_time_alter_hotel_checkout_time_and_more'),
        ('HMS_app', '0004_alter_roomimage_image_url'),
    ]

    operations = [
    ]
